CREATE TABLE IF NOT EXISTS KitRenta_CG (
ID_rent SERIAL PRIMARY KEY,
Type_kit VARCHAR,
Precio DECIMAL(10,2),
Descrpt VARCHAR
);
INSERT INTO KitRenta_CG (Type_kit, Precio, Descrpt)
VALUES 
('Kit Completo', 50.00, 'Marcadora, chaleco, camisola, careta y tanque Co2'),
('Tiro al Blanco', 30.00, 'Marcadora y tanque de Co2'),
('Bala', 1.00, 'Balas x Pza.');

SELECT * FROM KitRenta_CG;

---TRUNCATE TABLE Inventario_CG RESTART IDENTITY; *borrado de todos los datos*
---DELETE FROM KitRenta_CG WHERE id_rent > 2; *borrado de los datos mayores a 2 en id_rent (3, 4,)*

CREATE TABLE IF NOT EXISTS Inventario_CG (
ID_Equip SERIAL PRIMARY KEY,
CATEGORIA VARCHAR,	
NOMBRE_ARTICULO VARCHAR,
STATUS VARCHAR
);
INSERT INTO Inventario_CG (CATEGORIA, NOMBRE_ARTICULO, STATUS)
VALUES 
('ARMA', 'MARCADORA CRONUS', 'USO'),('ARMA', 'MARCADORA CRONUS', 'USO'),
('ARMA', 'MARCADORA CRONUS', 'USO'),('ARMA', 'MARCADORA CRONUS', 'USO'),
('ARMA', 'MARCADORA CRONUS', 'USO'),('ARMA', 'MARCADORA CRONUS', 'USO'),
('ARMA', 'MARCADORA CRONUS', 'USO'),('ARMA', 'MARCADORA TIPPMAN 98', 'USO'),
('ARMA', 'MARCADORA TIPPMAN 98', 'USO'),('ARMA', 'MARCADORA TIPPMAN 98', 'USO'),
('ARMA', 'MARCADORA TIPPMAN 98', 'USO'),('ARMA', 'MARCADORA TIPPMAN 98', 'USO'),
('ARMA', 'MARCADORA TANGO ONE', 'USO'),('ARMA', 'MARCADORA TANGO ONE', 'USO'),
('ARMA', 'MARCADORA L TIPPMAN', 'USO'),('ARMA', 'MARCADORA L TIPPMAN', 'USO'),
('PROTECCION','CARETA V FORCE', 'USO'), ('PROTECCION','CARETA V FORCE', 'USO'),
('PROTECCION','CARETA JT', 'USO'),('PROTECCION','CARETA JT', 'USO'),
('PROTECCION','CARETA JT', 'USO'),('PROTECCION','CARETA JT', 'USO'),
('PROTECCION','CARETA JT', 'USO'),('PROTECCION','CARETA JT', 'USO'),
('PROTECCION','CARETA JT', 'USO'),('PROTECCION','CARETA JT', 'USO'),
('PROTECCION','CARETA JT', 'USO'),('PROTECCION','CARETA JT', 'USO'),
('PROTECCION','CARETA JT', 'USO'),('PROTECCION','CARETA JT', 'USO'),
('PROTECCION','CARETA JT', 'USO'),('PROTECCION','CARETA JT', 'USO'),
('PROTECCION','CARETA JT', 'USO'),('PROTECCION','CARETA JT', 'USO'),
('PROTECCION','CHALECO CAMU', 'USO'),('PROTECCION','CHALECO CAMU', 'USO'),
('PROTECCION','CHALECO CAMU', 'USO'),('PROTECCION','CHALECO CAMU', 'USO'),
('PROTECCION','CHALECO CAMU', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CHALECO BLACK', 'USO'),
('PROTECCION','CHALECO BLACK', 'USO'),('PROTECCION','CAMISOLA CAMU', 'USO'),
('PROTECCION','CAMISOLA CAMU', 'USO'),('PROTECCION','CAMISOLA CAMU', 'USO'),
('PROTECCION','CAMISOLA CAMU', 'USO'),('PROTECCION','CAMISOLA CAMU', 'USO'),
('PROTECCION','CAMISOLA CAMU', 'USO'),('PROTECCION','CAMISOLA CAMU', 'USO'),
('PROTECCION','CAMISOLA CAMU', 'USO'),('PROTECCION','CAMISOLA CAMU', 'USO'),
('PROTECCION','CAMISOLA CAMU', 'USO'),('PROTECCION','CAMISOLA BEIGE', 'USO'),
('PROTECCION','CAMISOLA BEIGE', 'USO'),('PROTECCION','CAMISOLA BEIGE', 'USO'),
('PROTECCION','CAMISOLA BEIGE', 'USO'),('PROTECCION','CAMISOLA BEIGE', 'USO'),
('PROTECCION','CAMISOLA BEIGE', 'USO'),('PROTECCION','CAMISOLA BEIGE', 'USO'),
('PROTECCION','CAMISOLA BEIGE', 'USO'),('PROTECCION','CAMISOLA BEIGE', 'USO'),
('PROTECCION','CAMISOLA BEIGE', 'USO'),('UTILIDAD','Co2 20', 'USO'),
('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),
('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),
('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),
('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),
('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),('UTILIDAD','Co2 20', 'USO'),
('UTILIDAD','Co2 10', 'USO'),('UTILIDAD','Co2 10', 'USO'),('UTILIDAD','Co2 10', 'USO'),
('UTILIDAD','Co2 10', 'USO'),('UTILIDAD','Co2 10', 'USO'),('UTILIDAD','Co2 10', 'USO'),
('UTILIDAD','Co2 10', 'USO'),('UTILIDAD','Co2 10', 'USO'),('UTILIDAD','Co2 10', 'USO'),
('UTILIDAD','Co2 10', 'USO'),('UTILIDAD','Co2 10L', 'USO'),('UTILIDAD','Co2 10L', 'USO'),
('UTILIDAD','Co2 10L', 'USO'),('CONSUMIBLE','BOLSA BALA', '28B');

ALTER TABLE Inventario_CG
ADD COLUMN Costo_unitario NUMERIC(10,2) DEFAULT 0;

UPDATE
Inventario_CG set Costo_unitario = 3000 where CATEGORIA = 'ARMA';
UPDATE
Inventario_CG set Costo_unitario = 500 where NOMBRE_ARTICULO like 'CARETA%';
UPDATE
Inventario_CG set Costo_unitario = 200 where NOMBRE_ARTICULO = 'Co2 20';
UPDATE
Inventario_CG set Costo_unitario = 150 where NOMBRE_ARTICULO = 'Co2 10';
UPDATE
Inventario_CG set Costo_unitario = 0.275 where CATEGORIA = 'CONSUMIBLE';

SELECT * FROM Inventario_CG

CREATE OR REPLACE VIEW Vista_Inversion_Categorias AS
SELECT 
    CATEGORIA, 
    SUM(Costo_unitario) as Inversion_Total,
	STATUS
FROM Inventario_CG 
where CATEGORIA <> 'CONSUMIBLE'
GROUP BY CATEGORIA,
STATUS;

CREATE OR REPLACE VIEW Vista_Inversion_Total AS
SELECT SUM (Inversion_Total) AS K_TOTAL_INVERTIDO
FROM Vista_Inversion_Categorias
where CATEGORIA <> 'CONSUMIBLE'

SELECT 
	(select K_TOTAL_INVERTIDO from Vista_Inversion_Total) / Precio as Q_rent
FROM KitRenta_CG
WHERE Type_kit = 'Kit Completo'


SELECT 
	(select Inversion_Total from Vista_Inversion_Categorias WHERE CATEGORIA = 'PROTECCION') / Precio as Q_rent
FROM KitRenta_CG
WHERE Type_kit = 'Kit Completo'

SELECT 
	(select Inversion_Total from Vista_Inversion_Categorias WHERE CATEGORIA = 'ARMA') / Precio as Q_rent
FROM KitRenta_CG
WHERE Type_kit = 'Kit Completo'

SELECT 
	(select Inversion_Total from Vista_Inversion_Categorias WHERE CATEGORIA = 'UTILIDAD') / Precio as Q_rent
FROM KitRenta_CG
WHERE Type_kit = 'Kit Completo'

